# Generated by Django 5.1.4 on 2024-12-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('hour', models.DateTimeField(help_text='Start of an hour of energy usage.', primary_key=True, serialize=False, verbose_name='Hour')),
                ('kwh', models.DecimalField(decimal_places=4, help_text='Amount of energy used, in kilowatt-hours (kWh) in an hour.', max_digits=7, verbose_name='Kilowatt-Hours (kWh)')),
            ],
            options={
                'verbose_name': 'Energy Usage',
                'verbose_name_plural': 'Energy Usage',
                'db_table': 'usage',
                'ordering': ('-hour',),
                'managed': True,
            },
        ),
    ]
